# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Nordeste 2015"
email: "ne@devfest.com.br"
description: "DevFest Nordeste"
baseurl: ""
url: "https://2015.devfestne.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "devfestne.com.br"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Recife"
organizerAlternateName: "Google Developer Group Recife"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "contato@gdgrecife.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgrecife.com"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/bftC5D"
c4sponsorsUrl: "/assets/Media_Kit_DevFest_NE_15.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Evento"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Programação"}
 - {permalink: "/speakers/", text: "Palestrantes"}
# - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logística"}
 - {permalink: "/#caravans", text: "Caravanas"}
 - {permalink: "http://2014.devfestne.com.br", text: "2014"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://www.even.tc/gdg-devfest-nordeste-2015", text: "Inscreva-se!"}
rightNavigationButtons:
 - {link: "http://www.even.tc/gdg-devfest-nordeste-2015", text: "Inscreva-se!"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2015"
eventDate: "17 de Outubro, 2015"
typeoutTextValues: '"", "Nordeste", "Recife", "Aracaju", "Maceió", "Fortaleza", "Hellcife"'
typeoutFallback: "Nordeste"
heroButtons:
 - {link: "https://goo.gl/bftC5D", text: "Seja um palestrante"}
 - {link: "http://eepurl.com/btF53v", text: "Seja um patrocinador"}
 - {permalink: "/#tickets", text: "Faça sua Inscrição"}

# About Block
aboutTitle: "Sobre o DevFest Nordeste"
aboutBlock:
 - {title: "Conferência", image: "conference.jpg", text: "O maior evento da comunidade Google nordestina! Palestrantes impressionantes e muita diversão!" }
 - {title: "Palestras", image: "workshop.jpg", text: "Googlers e membros da comunidade falando sobre tecnologias mobile, web e emprendedorismo!" }
 - {title: "Experimentos", image: "hackathon.jpg", text: "Uma área com exposição de tecnologias e experimentos!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "participantes", detail: "de todo Nordeste"}
 - {count: "18", specialCharacter: "+", info: "palestrantes", detail: "e especialistas de tecnologia"}
 - {count: "20", specialCharacter: "+", info: "horas", detail: "de pura tecnologia Google"}
 - {count: "3", specialCharacter: "+", info: "trilhas paralelas", detail: "e muitas novidades"}

# Latest News Block
latestNewsTitle: "Últimas Notícias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Palestrantes Rockstars"
rockstarSpeakersButtonText: "Ver todos palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Recife Antigo"
eventLocationLink: "#"
eventStreetAddress: "Praça Rio Branco (Marco Zero)"
eventAddressLocality: "Bairro do Recife"
eventAddressLocalityRegion: "Pernambuco"
eventPostalCode: "79000"
eventAddressCountry: "Brasil"
eventStartTime: "2015-10-17T09:00"
eventDoorTime: "08:00"
eventEndTime: "2015-10-17T19:00"
eventPlaceCoordinates: "-8.063149, -34.871311"
mapCenterCoordinates: "-8.063149, -34.874414"
mapMobileCenterCoordinates: "-8.063149, -34.871311"

# Venue Block
venueBlockTitle: "O[s] Lugar[es]"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Recife Antigo"
venueFeatures: ["Polos com palestras e experimentos", "Atrações culturais", "Localizado no coração histórico de Recife"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "devfestne15"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&user=devfestne&cache_interval=8000"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Seja um Patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Ingressos"
ticketsInfo: "Os ingressos dão direito ao acesso a todas as trilhas, palestras e coffe-breaks no evento. Estadia <strong>não está</strong> inclusa no preço da ingressos. Confira a seção de <a href='/logistics/'>logística</a> para saber onde se hospedar (com desconto!) em Recife."
ticketsOffers:
 -
  name: "Super Early Bird"
  price: "60"
  priceCurrency: "R$"
  ticketsNumber: "150"
#  ribbon: "-25%"
  buyButtonLink: "http://www.even.tc/gdg-devfest-nordeste-2015"
  buyButtonText: "Compre agora!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-08-25T10:00"
  validThrough: "2015-09-27T23:59"
 -
  name: "Early Bird"
  price: "80"
  disabled: true
  priceCurrency: "R$"
  ticketsNumber: "0"
  buyButtonLink: "http://www.even.tc/gdg-devfest-nordeste-2015"
  buyButtonText: "Compre agora!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-08-28T00:00"
  validThrough: "2015-10-10T23:59"
 -
  name: "Late Bird"
  price: "105"
  disabled: true
  priceCurrency: "R$"
  ticketsNumber: "0"
  buyButtonLink: "http://www.even.tc/gdg-devfest-nordeste-2015"
  buyButtonText: "Compre agora!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-10-10T00:00"
  validThrough: "2015-10-17T05:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=devfestne", icon: "twitter"}
 - {link: "https://facebook.com/devfestne", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgrecife.com", text: "GDG Recife"}
   - {link: "http://gdgaracaju.com.br", text: "GDG Aracaju"}
   - {link: "http://gdgmaceio.rocks", text: "GDG Maceió"}
   - {link: "http://gdgfortaleza.org", text: "GDG Fortaleza"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:ne@devfest.com.br", text: "ne@devfest.com.br"}
 -
  title: "FAQ"
  links:
   - {permalink: "http://pt-br.confcodeofconduct.com", text: "Código de Conduta"}

# Blog
blogTitle: "Blog"
blogCommentsEnabled: false
discusShortName: "devfestne"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: ""
findWayDistance: "Distância"
findWayDriving: "Carro"
findWayWalking: "A pé"
findWayBicycling: "Bicicleta"
findWayTransit: "Ônibus e Metrô"
findWayFindFlight: "Procure um Voo"
logisticsMapCenterCoordinates: "-8.063149, -34.874414"
logisticsMapMobileCenterCoordinates: "-8.063149, -34.874414"
logisticsMapAutoDirections: true

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Eu vi o mundo... Ele começava no Recife"
directionDetailsCards:
 - {title: "Aeroporto", information: 'O Aeroporto Internacional Guararapes-Gilberto Freyre está localizado a 20 minutos do Recife Antigo. É fácil ir e voltar para ele usando metrô, ônibus ou táxi. Mais informações no <a href="http://www.aeroportorecife.net/">site do aeroporto</a>.'}
 - {title: "Ônibus e Metrô", information: 'O Google Transit está disponível em Recife. Então, você consegue usa-lo dentro do Google Maps. Você também pode baixar o <a href="https://play.google.com/store/apps/details?id=br.com.cittabus">CittaBus</a>, <a href="https://play.google.com/store/apps/details?id=me.luish.busrec">Busão Recife</a> ou <a href="https://play.google.com/store/apps/details?id=com.dom925.trainsity.recife">Trainsity Recife Metro</a> para se localizar melhor. Todos gratuitos para Android.'}
# - {title: "Táxis", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
 - {title: "Hotéis e Hostels", information: 'Recife tem excelentes hotéis e hostels disponíveis. Veja algumas opções abaixo para ficar durante o fim de semana. Consiga até 25% de desconto nas nossas estadias oficiais.'}
#directionDetailsWideCards:
# -
#  title: "Hostels"
#  subCards:
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.840696, 24.028754"

# Caravan Block
caravanTitle: "Caravanas Oficiais"
caravanFrom: "De"
caravanResponsible: "Responsável"
caravanLinkTitle: "Participar da Caravana"
caravansInfo: "As caravanas são organizadas por membros do GDG de outros estados."
caravansUrl: "https://docs.google.com/forms/d/1OLVGqJuR2CXMyeupaIUDq8ZJCqMdSWRp37x6QV_dNaA/viewform"
caravansButton: "Organize uma caravana!"
